title: Nguyen Bui # your name (or website title) here
logo: "/images/profile_photo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p>
  Hello,
  <p>
  My name is Nguyen Bui and I am a Software Engineering Intern at OmniPreSense.
  <p>
  Welcome to my project portfolio.
  <br>
  <br>
  <a href="https://www.linkedin.com/in/nguyen-bui-952b95a4/" target="_blank">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-TV41RPZZ6C # your Google Analytics tracking ID here
