title: Nguyen Bui # your name (or website title) here
logo: "/images/profile_photo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p>
  Hello,
  <p>
  My name is Nguyen Bui and I am a software engineering intern at OmniPreSense.
  <p>
  Welcome to my personal website.
  <br>
  <br>
  <a href="https://www.linkedin.com/in/nguyen-bui-952b95a4/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
